# DataCharts System Docker Compose Configuration
version: '3.8'

services:
  datacharts-backend:
    build: .
    container_name: datacharts-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - MAX_FILE_SIZE=52428800  # 50MB
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  datacharts-frontend:
    image: nginx:alpine
    container_name: datacharts-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - datacharts-backend
    restart: unless-stopped

volumes:
  data:
    driver: local
  logs:
    driver: local
  uploads:
    driver: local

networks:
  default:
    name: datacharts-network
